### ISSUE TITLE
snakemake找不到srcdir函数

### ISSUE THREAD

**Issue by summersohot** [epigen/unsupervised_analysis#43]
I am a novice, I am currently using your library, but I have some problems, I do not know how to solve
Here are the wrong questions

Traceback (most recent call last):

  File "/home/wang/miniconda3/envs/snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 1893, in args_to_api

    dag_api = workflow_api.dag(

              ^^^^^^^^^^^^^^^^^

  File "/home/wang/miniconda3/envs/snakemake/lib/python3.12/site-packages/snakemake/api.py", line 326, in dag

    return DAGApi(

           ^^^^^^^

  File "<string>", line 6, in __init__

  File "/home/wang/miniconda3/envs/snakemake/lib/python3.12/site-packages/snakemake/api.py", line 436, in __post_init__

    self.workflow_api._workflow.dag_settings = self.dag_settings

    ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/wang/miniconda3/envs/snakemake/lib/python3.12/site-packages/snakemake/api.py", line 383, in _workflow

    workflow.include(

  File "/home/wang/miniconda3/envs/snakemake/lib/python3.12/site-packages/snakemake/workflow.py", line 1379, in include

    exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals)

  File "/home/wang/rna/unsupervised_analysis/workflow/Snakefile", line 10, in <module>

    SDIR = os.path.realpath(os.path.dirname(srcdir("Snakefile")))

                                                        ^^^^^^

NameError: name 'srcdir' is not defined

**Comment by sreichl** [comment]
Hi, thanks for reaching out.
Which Snakemake version are you using?
I think you can simply comment/remove this line and the error will resolve as the latest Snakemake version does not support the ```srcdir``` function anymore. I will tackle this issue as soon as possible, but this should enable you to get going.

If you find this repository useful, please consider starring it.

Thanks & Cheers, Stephan

**Comment by summersohot** [comment]
Thank you, reply to my content, but also thank you for your selfless contribution
I'm using version 8.4.3,
1. I am currently running with your sample data
2. If possible, could you please ask me again about writing your own data format in the template, I just came across the snakemake workflow and I think it is great

**Comment by summersohot** [comment]
This is what I ran with the sample data, can I ask you about it
Maybe I'm a little rusty


[1.txt](https://github.com/epigen/unsupervised_analysis/files/14165709/1.txt)

**Comment by sreichl** [comment]
It seems that the heatmap plotting throws this error: died with <Signals.SIGKILL: 9>
I am not familiar with it. It sounds like something with your system? Maybe an issue with your allocated resources e.g., memory or number of cpus?
There should be an error file explicitly for this rule in the /log folder that might be more helpful.

**Comment by summersohot** [comment]
Thank you for your reply, let me learn knowledge
